name: System_Pulse_Orchestrator

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *' # Теперь пульс каждый час, чтобы данные были свежими
  workflow_dispatch:

jobs:
  refresh_original:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout Original
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mass Infrastructure Scan
        run: |
          echo "📡 Сканирование Массы (microsoft/vscode)..."
          # Получаем дату последнего движения в VS Code
          MASS_DATE=$(curl -s https://api.github.com/repos/microsoft/vscode/commits/main | grep '"date":' | head -n 1 | sed 's/[^0-9T:-]//g')
          echo "MASS_LAST_ACTIVITY=$MASS_DATE" >> $GITHUB_ENV
          # Создаем JSON для сайта
          echo "{\"last_pulse\": \"$MASS_DATE\", \"status\": \"OPERATIONAL\", \"origin\": \"msftgits-legacy\"}" > status.json

      - name: System Reset & Injection
        run: |
          git config --global user.name "msftgits"
          git config --global user.email "msftgits@microsoft.com"

          # Обновление твоей секретной базы .env
          echo "LAST_PULSE=$(date +'%Y-%m-%d %H:%M:%S')" > .env
          echo "MASS_PULSE=${{ env.MASS_LAST_ACTIVITY }}" >> .env
          echo "SYSTEM_STATUS=OPERATIONAL" >> .env

          git add .
          if git diff --staged --quiet; then
            echo "Изменений нет."
          else
            git commit -m "🌀 System Pulse: Integrated Mass Activity [${{ env.MASS_LAST_ACTIVITY }}]"
            git push origin main
          fi

      # --- Секция публикации на твой сайт ---
      - name: Build and Upload Pages
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
